languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = "true"
enableEmoji = "true"

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://gshirato.github.io/"
title = "Gota Shirato @University of Bonn"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
